# Dockerfile for MySQL
FROM mysql:5.7

# 環境変数を設定
ENV MYSQL_DATABASE wordpress
ENV MYSQL_USER wordpress_user
ENV MYSQL_PASSWORD wordpress_password
ENV MYSQL_ROOT_PASSWORD root_password

# ポートを開放
EXPOSE 3306