# Dockerfile for WordPress
FROM wordpress:latest

# WordPressとMySQLの接続情報
ENV WORDPRESS_DB_HOST db:3306
ENV WORDPRESS_DB_USER wordpress_user
ENV WORDPRESS_DB_PASSWORD wordpress_password
ENV WORDPRESS_DB_NAME wordpress

# ポートを開放
EXPOSE 80